### ISSUE TITLE
WebSocket handshake: Unexpected response code: 301

### ISSUE THREAD

**Issue by chloridrik** [wit-ai/microphone#15]
Hi,

I was working few days ago with the Microphone and it was working well.
Today I have an erreur when I do mic.connect(clientToken), I have this message : 

WebSocket connection to 'wss://api.wit.ai/speech_ws' failed: Error during WebSocket handshake: Unexpected response code: 301

My web page is in local with an https and the host is registred in the wit admin console.
I have reset the tocken but the problem persist.

thx,
Jeremie.

**Comment by sylmanu** [comment]
Hi,

I have got the same issue here too. According to the article below It seems that the HTTP error 301 indicates that the server has been moved to another URL but I still wonder how to solve the issue... http://www.checkupdown.com/status/E301.html

**Comment by blandinw** [comment]
Hi, we are in the process of moving to a new infra (see https://wit.ai/blog/2017/02/10/wit-community-update).
This new infra cannot accept websocket connections on api.wit.ai, so we created ws.wit.ai and started redirecting (301) to this new domain.

Unfortunately, we did not expect the fact that `ws` (the JS library for websocket that we use) does not follow redirects and instead throws an error. 

We'll publish a new version of microphone.js today to use ws.wit.ai instead of api.wit.ai as a domain name.
In the meantime, you can use `localStorage.setItem('wit_ws', 'wss://ws.wit.ai/speech_ws')` to override the default host.

**Comment by blandinw** [comment]
Here is the new release: https://github.com/wit-ai/microphone/releases/tag/0.8.2
Running at https://labs.wit.ai/demo/index.html.

Sorry for the inconvenience and thank you for your patience.

**Comment by sylmanu** [comment]
Thanks, it is working now!

**Comment by JoabMendes** [comment]
Nice, you guys should update the docs as well.

**Comment by blandinw** [comment]
@JoabMendes which docs are you referring to?

**Comment by JoabMendes** [comment]
@blandinw The [quickstart.md](https://github.com/wit-ai/microphone/blob/master/quickstart.md) has the 0.7 version on the step 1, not the latest one.
